apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kt-deepseek-harness
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: deepseek-harness-nginx
    files:
      - dsh-web.conf
    options:
      disableNameSuffixHash: true
images:
  - name: ghcr.io/ktaiorg/deepseek-harness
    newName: ghcr.io/ktaiorg/deepseek-harness
    newTag: sha-000000000000
